### ISSUE TITLE
Proposal to fork this repo under a community Afterglow Organization

### ISSUE THREAD

**Issue by bmcminn** [YabataDesign/afterglow-theme#125]
In response to #120, and the fact that @YabataDesign hasn't publicly contributed to Github or their Behance profile since May of 2015, I'm proposing that we create an Afterglow Organization to house the _new_ official fork of this theme which is currently maintained at https://github.com/vikjam/afterglow-theme.

I feel this is the best course of action as a sizeable community has built around Afterglow, and recentralizing things would allow for more people to contribute.

@vikjam @mknabe

Feel free to tag others, but since I've seen y'all active in the issue comments, I figured I'd add y'all directly.

**Comment by vikjam** [comment]
I'm happy to help in any way to keep this theme actively developed! I had a couple of quick questions:

* Can/should we keep the same name? I had thought of renaming the fork Afterglow X or something, but I hadn't felt confident enough in doing that until I had made some significant changes.
* If we keep the same name, will we be able to redirect Package Control to the repository under the Organization?

I'm also curious to hear what other folks using Afterglow think is best.

**Comment by kaansoral** [comment]
I personally changed the "variable" color to white lately, after that, it holds it's own against the recent ST3 updates, I'm sure most people at this point either modifies the theme themselves or use the fork (i)

I think, the best course of action is to go the "Afterglow X" route, with separate Package Control + Colorscheme Plugin entries, since @YabataDesign is not around to object, I think it would be the easiest route for the community

So, basically, a new/reborn colorscheme, that uses the original Afterglow as reference

-- -- --

Off topic, I also tried to replace Afterglow with something else, tested many colorschemes, used this for a week: https://github.com/IceTimux/one-dark-sublime-text-3-color-scheme (awesome colorscheme) - yet, after all that time, I'm still back at Afterglow, the color choices are just so mellowly awesome

So, I'm also worried that, this new fork, might make some bad color choices for new syntax additions [I went with white in (i) - as originally most stuff was white]

**Comment by bmcminn** [comment]
@vikjam it may be possible to contact package control about handling this kind of situation where the package manager is no longer active in maintaining a resource. Will Bond has an email link so I can try reaching out to him and see what his policy is in this kind of situation.

As for renaming the package, it makes sense. I think attribution to @YabataDesign would be appropriate in that case, but considering people like the theme for its color scheme, I see no reason to change it. Just improve upon the base theme so people who use different technologies are better supported going forward. New color schemes could probably be added in the form of alternate theme setting parameters similar to Afterglow blue, red, lime, etc.

**Comment by mknabe** [comment]
Thank you for starting this up @bmcminn. I only occasionally make contributions here, so I will defer to others. 

I do think a new name like "Afterglow X" is the best route.

**Comment by jackolney** [comment]
Great idea to fork this repo – it is a real shame that @YabataDesign is no longer keeping it active, but @vikjam has done a great job in picking up the slack. I myself have actually switched to the material-design theme, but still do miss how great Afterglow was. I like the idea of a re-name but instead of "Afterglow X", what about "AfterGlow" in Pascal-case or "AfterGlow3" hinting at its link specifically to ST3.

**Comment by egeerardyn** [comment]
@jackolney I think `AfterGlow` looks nice (the old Pascaller in me, actually wants to type `Afterglow` as `AfterGlow` all the time), but the change is too subtle for its own good. Similarly, `AfterGlow3` might be too coupled to ST3 (e.g. what if somebody decides to port it to Atom, what when ST4 comes around, ...)

@vikjam I concur: we should really rename the project to avoid confusion. I think it deserves its own name, but just adding a neutral suffix to the theme might make it easier to find in Package Control.

Maybe we can combine both: **AfterGlow X**, **AfterGlow Neo**, ...

**Comment by jackolney** [comment]
@egeerardyn _sigh_ I agree, `AfterGlow` is too subtle for most. And wishful thinking about ST4 :wink:

+1 for `AfterGlow X` or a contraction to `AfterGlowX`

**Comment by vikjam** [comment]
If we wanted to be cheeky we could use **AfterAfterglow** or a nerdy option would be [**Alpenglow**](https://en.wikipedia.org/wiki/Alpenglow).

In any case, I definitely agree we should make sure @YabataDesign gets very prominently attributed.

@evansendra has [a fork of the icon](https://github.com/evansendra/sublime-text-icon) with updated instructions on how to install it. It'd probably make sense for that to be folded under the organization as well.

**Comment by egeerardyn** [comment]
@vikjam : :+1: for AlpenGlow, I thought about that one as well. I didn't suggest it, because in my head Alps are more blue-ish/white-ish than this theme. But it certainly is a distinctive name.

**Comment by jackolney** [comment]
**AlpenGlow** is a _great_ name!

**Comment by bmcminn** [comment]
I went ahead and started the https://github.com/AlpenglowTheme Organization and added everyone from this issue thread. I've also cloned @vikjam's Afterglow fork and pushed the assets to the new https://github.com/AlpenglowTheme/alpenglow-theme repository, updating asset names from Afterglow to the new Alpenglow moniker.

I'll be out of town tomorrow, however if anyone wants to test it out and see if the new name has been correctly applied, feel free. Otherwise I think we can close this issue and file a new one here to help redirect folks to the new repository :)

:confetti_ball: :tada: :clap: 

Also, if anyone wants to be an Owner in the organization, let me know by adding a :+1: reaction to this issue: https://github.com/AlpenglowTheme/alpenglow-theme/issues/2
