### ISSUE TITLE
(Windows 7) Italics are shown on Tab Buttons

### ISSUE THREAD

**Issue by zachcowell** [YabataDesign/afterglow-theme#37]
Installed the theme on my OS X and Windows machines. For some reason, the tab buttons are in italics on the Windows machine. Is there any way to remove the italics?

Thanks & love the great theme!

![capture2](https://cloud.githubusercontent.com/assets/2313483/6597920/5010c730-c7d6-11e4-9da1-526ec88f7704.PNG)

**Comment by joevp** [comment]
Open your *.sublime-theme file and remove the line for "font.italic": true

https://github.com/YabataDesign/afterglow-theme/blob/master/Afterglow.sublime-theme#L176

**Comment by zachcowell** [comment]
Awesome, that did it. Thanks!

**Comment by sisou** [comment]
It's really annoying to have to do that after each new release! Like there were like 4 releases in the last couple days... always have to change that line... Why is it in italics anyway?

**Comment by YabataDesign** [comment]
Thank you very much for your comments. I wanted to mention to several things:

1. This theme, like everyone in Sublime Text, is free. Nobody has forced me to upload it. I just built it because no other theme I liked, and then decided to share it.

2. Lately I have very little time to resolve these issues. Patience is appreciated.

3. This functionality is contradicted by another that has already been resolved (#16).

4. The way to resolve this contradiction is through user preferences, and that takes some time. Not only delete a line that I added because another user requested me.

I hope to have time to resolve this issue and others pending.

Thanks so much.

**Comment by sisou** [comment]
I am sorry. I sincerely apologise for my classical hater behavior.

I do see now that I have no right to criticise other people's work and that your design is yours and yours alone. I did not realise that my opinion on tabs was not everyone's opinion. I always thought, italic tabs are an error of some kind... *stupid*.

Sorry again, I usually do not take everything that's free for granted.

That being said, I will look into creating a pull request for the addition of a new setting and post it here ;).

BTW, thanks for the (otherwise) awesome theme! ;-)
